const ALL_CARDS = [
  {id:'c1', cost:1, name:'ゴブリン', type:'ユニット', atk:1, hp:2, keyword:'', trigger:'', effect:'', aiRole:''},
  {id:'c2', cost:1, name:'ウィスプ', type:'ユニット', atk:1, hp:1, keyword:'先制', trigger:'', effect:'', aiRole:''},
  {id:'c3', cost:1, name:'カーバンクル', type:'ユニット', atk:0, hp:1, keyword:'', trigger:'死亡時', effect:'1ドローする', aiRole:''},
  {id:'c4', cost:1, name:'水精の清め', type:'スペル', atk:0, hp:0, keyword:'', trigger:'', effect:'対象を3点回復', aiRole:'healSpell'},
  {id:'c5', cost:1, name:'土精の足枷', type:'スペル', atk:0, hp:0, keyword:'', trigger:'', effect:'敵ユニット一体に-2/0デバフ', aiRole:''},
  {id:'c6', cost:2, name:'コボルト', type:'ユニット', atk:2, hp:2, keyword:'', trigger:'', effect:'', aiRole:''},
  {id:'c7', cost:2, name:'ハーピー', type:'ユニット', atk:1, hp:1, keyword:'', trigger:'登場時', effect:'1/1トークンを召喚', aiRole:''},
  {id:'c8', cost:2, name:'マーメイド', type:'ユニット', atk:1, hp:2, keyword:'守護', trigger:'', effect:'', aiRole:''},
  {id:'c9', cost:2, name:'スライム', type:'ユニット', atk:2, hp:1, keyword:'', trigger:'死亡時', effect:'1/1トークンを召喚', aiRole:''},
  {id:'c10', cost:2, name:'火精の火遊び', type:'スペル', atk:0, hp:0, keyword:'', trigger:'', effect:'ユニット一体に2点ダメージ', aiRole:''},
  {id:'c11', cost:2, name:'アローレイン', type:'スペル', atk:0, hp:0, keyword:'', trigger:'', effect:'敵ユニット全体に1点ダメージ', aiRole:''},
  {id:'c12', cost:2, name:'ホーリーベル', type:'陣地', atk:0, hp:0, keyword:'', trigger:'', effect:'自ユニット全体に+1/+1バフ（オーラ）', aiRole:''},
  {id:'c13', cost:3, name:'オーク', type:'ユニット', atk:3, hp:3, keyword:'', trigger:'', effect:'', aiRole:''},
  {id:'c14', cost:3, name:'ワーウルフ', type:'ユニット', atk:2, hp:2, keyword:'速攻', trigger:'', effect:'', aiRole:''},
  {id:'c15', cost:3, name:'ミノタウロス', type:'ユニット', atk:2, hp:3, keyword:'守護', trigger:'', effect:'', aiRole:''},
  {id:'c16', cost:3, name:'レヴナント', type:'ユニット', atk:2, hp:3, keyword:'', trigger:'死亡時', effect:'1/2トークンを手札に加える', aiRole:''},
  {id:'c17', cost:3, name:'スペクター', type:'ユニット', atk:2, hp:2, keyword:'障壁', trigger:'', effect:'', aiRole:''},
  {id:'c18', cost:3, name:'ラミア', type:'ユニット', atk:1, hp:3, keyword:'速攻・ドレイン', trigger:'', effect:'', aiRole:''},
  {id:'c19', cost:3, name:'戦乙女の激励', type:'スペル', atk:0, hp:0, keyword:'', trigger:'', effect:'自ユニット全体に+1/+1バフ', aiRole:'fieldBuff'},
  {id:'c20', cost:3, name:'アカシャの記録', type:'スペル', atk:0, hp:0, keyword:'', trigger:'', effect:'2枚ドローする', aiRole:''},
  {id:'c21', cost:3, name:'ミアズマの霧', type:'スペル', atk:0, hp:0, keyword:'', trigger:'', effect:'敵ユニット全体に-1/-1デバフ', aiRole:''},
  {id:'c22', cost:3, name:'聖泉の恵み', type:'スペル', atk:0, hp:0, keyword:'', trigger:'', effect:'対象を5点回復', aiRole:'healSpell'},
  {id:'c23', cost:3, name:'フェアリーベル', type:'陣地', atk:0, hp:0, keyword:'', trigger:'自ターン終了時', effect:'自ユニットのランダムな1体に+1/+1バフ', aiRole:'fieldBuff'},
  {id:'c24', cost:3, name:'反魔の聖陣', type:'陣地', atk:0, hp:0, keyword:'', trigger:'', effect:'相手が4マナ以下のスペル/陣地使用時に無効化して自壊', aiRole:''},
  {id:'c25', cost:4, name:'バクベア', type:'ユニット', atk:4, hp:4, keyword:'', trigger:'', effect:'', aiRole:''},
  {id:'c26', cost:4, name:'グリフォン', type:'ユニット', atk:5, hp:3, keyword:'', trigger:'', effect:'', aiRole:''},
  {id:'c27', cost:4, name:'ガーゴイル', type:'ユニット', atk:3, hp:4, keyword:'守護', trigger:'', effect:'', aiRole:''},
  {id:'c28', cost:4, name:'サンダーバード', type:'ユニット', atk:2, hp:3, keyword:'', trigger:'登場時', effect:'敵ユニット全体に2点ダメージ', aiRole:''},
  {id:'c29', cost:4, name:'ホムンクルス', type:'ユニット', atk:3, hp:3, keyword:'', trigger:'スペル使用時', effect:'バフ+1/+1', aiRole:'spellSynergy'},
  {id:'c30', cost:4, name:'ユニコーン', type:'ユニット', atk:1, hp:5, keyword:'', trigger:'回復時', effect:'バフ+1/+1', aiRole:'healSynergy'},
  {id:'c31', cost:4, name:'トールハンマー', type:'スペル', atk:0, hp:0, keyword:'', trigger:'', effect:'敵ユニット一体に4点ダメージ', aiRole:''},
  {id:'c32', cost:4, name:'精霊たちの宴', type:'スペル', atk:0, hp:0, keyword:'', trigger:'', effect:'自分と自ユニット全体を3点回復', aiRole:'healSpell'},
  {id:'c33', cost:5, name:'オーガ', type:'ユニット', atk:5, hp:5, keyword:'', trigger:'', effect:'', aiRole:''},
  {id:'c34', cost:5, name:'ティタン', type:'ユニット', atk:6, hp:4, keyword:'', trigger:'', effect:'', aiRole:''},
  {id:'c35', cost:5, name:'ペガサス', type:'ユニット', atk:4, hp:3, keyword:'速攻', trigger:'', effect:'', aiRole:''},
  {id:'c36', cost:5, name:'セラフィム', type:'ユニット', atk:3, hp:4, keyword:'守護・障壁', trigger:'', effect:'', aiRole:''},
  {id:'c37', cost:5, name:'ヴァンパイア', type:'ユニット', atk:2, hp:6, keyword:'ドレイン', trigger:'ターン終了時', effect:'ターン終了時にこのユニットのHPを2回復', aiRole:'healSynergy'},
  {id:'c38', cost:5, name:'シャイターン', type:'ユニット', atk:3, hp:3, keyword:'', trigger:'登場時', effect:'相手または敵ユニット一体に3点ダメージ', aiRole:''},
  {id:'c39', cost:5, name:'ドラゴンブレス', type:'スペル', atk:0, hp:0, keyword:'', trigger:'', effect:'敵ユニット全体に3点ダメージ', aiRole:'boardClear'},
  {id:'c40', cost:5, name:'快癒の光', type:'スペル', atk:0, hp:0, keyword:'', trigger:'', effect:'対象を8点回復', aiRole:'healSpell'},
  {id:'c41', cost:5, name:'霊薬-エリクシール', type:'スペル', atk:0, hp:0, keyword:'', trigger:'', effect:'2枚ドローし5点回復', aiRole:'healSpell'},
  {id:'c42', cost:5, name:'不死鳥の揺籃', type:'陣地', atk:0, hp:0, keyword:'', trigger:'HP0時', effect:'HPを5にして自壊', aiRole:'emergencyHeal'},
  {id:'c43', cost:6, name:'フェニックス', type:'ユニット', atk:3, hp:3, keyword:'', trigger:'死亡時', effect:'4/4トークンを召喚', aiRole:''},
  {id:'c44', cost:6, name:'タラスク', type:'ユニット', atk:5, hp:5, keyword:'', trigger:'攻撃時', effect:'+2/0バフ', aiRole:''},
  {id:'c45', cost:6, name:'ヴァルキリー', type:'ユニット', atk:4, hp:4, keyword:'', trigger:'登場時', effect:'自ユニット全体に+1/+1バフ', aiRole:'fieldBuff'},
  {id:'c46', cost:7, name:'アングルボザの子供達', type:'スペル', atk:0, hp:0, keyword:'', trigger:'', effect:'3/3先制・2/2ドレイン・1/1必殺トークンを召喚', aiRole:'fieldBuff'},
  {id:'c47', cost:6, name:'破壊の言霊', type:'スペル', atk:0, hp:0, keyword:'', trigger:'', effect:'ユニット一体または陣地一つを破壊', aiRole:''},
  {id:'c48', cost:2, name:'ファウストの契約書', type:'陣地', atk:0, hp:0, keyword:'', trigger:'自ターン開始時', effect:'1点ダメージを受け1ドローする', aiRole:''},
  {id:'c49', cost:7, name:'エンプーサ', type:'ユニット', atk:4, hp:5, keyword:'速攻・隠密', trigger:'', effect:'', aiRole:''},
  {id:'c50', cost:7, name:'スフィンクス', type:'ユニット', atk:3, hp:7, keyword:'先制・守護', trigger:'', effect:'', aiRole:''},
  {id:'c51', cost:7, name:'エキドナ', type:'ユニット', atk:2, hp:4, keyword:'', trigger:'登場時', effect:'1/2トークンを最大4体召喚', aiRole:''},
  {id:'c52', cost:7, name:'ラグナロク', type:'スペル', atk:0, hp:0, keyword:'', trigger:'', effect:'全てのユニットを破壊', aiRole:'boardClear'},
  {id:'c53', cost:8, name:'鷲獅子の黄金洞', type:'陣地', atk:0, hp:0, keyword:'至高', trigger:'相手ターン終了時', effect:'グリフォンを召喚', aiRole:''},
  {id:'c54', cost:8, name:'ヒルド', type:'ユニット', atk:4, hp:6, keyword:'', trigger:'登場時', effect:'自ユニット全体に+2/+2バフ', aiRole:'fieldBuff'},
  {id:'c55', cost:8, name:'スキュラ', type:'ユニット', atk:5, hp:5, keyword:'', trigger:'登場時', effect:'敵全体に2点ダメージ', aiRole:''},
  {id:'c56', cost:8, name:'ジャバウォック', type:'ユニット', atk:7, hp:5, keyword:'貫通・障壁', trigger:'', effect:'', aiRole:''},
  {id:'c57', cost:8, name:'煉獄-プルガトリオ', type:'スペル', atk:0, hp:0, keyword:'', trigger:'', effect:'敵ユニット全体に5点ダメージ', aiRole:'boardClear'},
  {id:'c58', cost:9, name:'マンティコア', type:'ユニット', atk:8, hp:5, keyword:'速攻', trigger:'', effect:'', aiRole:'finisher'},
  {id:'c59', cost:9, name:'イフリート', type:'ユニット', atk:6, hp:4, keyword:'', trigger:'登場時', effect:'相手と敵ユニット全体に3点ダメージ', aiRole:'finisher'},
  {id:'c60', cost:10, name:'騒乱-スタンピード', type:'陣地', atk:0, hp:0, keyword:'', trigger:'', effect:'自ユニット全体に貫通付与と+3/0バフ', aiRole:'fieldBuff'},
  {id:'c61', cost:2, name:'万陣破', type:'スペル', atk:0, hp:0, keyword:'', trigger:'', effect:'陣地ひとつを破壊', aiRole:''},
  {id:'c62', cost:2, name:'ジャーンの書', type:'スペル', atk:0, hp:0, keyword:'', trigger:'', effect:'2枚ドローし1枚選んで捨てる', aiRole:''},
  {id:'c63', cost:1, name:'インプ', type:'ユニット', atk:2, hp:1, keyword:'', trigger:'', effect:'', aiRole:''},
  {id:'c64', cost:1, name:'ピクシー', type:'ユニット', atk:0, hp:3, keyword:'守護', trigger:'', effect:'', aiRole:''},
  {id:'c65', cost:2, name:'ベルセルク', type:'ユニット', atk:3, hp:1, keyword:'', trigger:'', effect:'', aiRole:''},
  {id:'c66', cost:2, name:'ケットシー', type:'ユニット', atk:1, hp:2, keyword:'', trigger:'攻撃時', effect:'1枚ドローする', aiRole:''},
  {id:'c67', cost:2, name:'ドリアード', type:'ユニット', atk:0, hp:2, keyword:'', trigger:'ターン終了時', effect:'他のランダムな自ユニット1体に+1/+1バフ', aiRole:'fieldBuff'},
  {id:'c68', cost:2, name:'ジン', type:'ユニット', atk:1, hp:2, keyword:'', trigger:'登場時', effect:'敵ユニット一体に1点ダメージ', aiRole:''},
  {id:'c69', cost:2, name:'風精の追い風', type:'スペル', atk:0, hp:0, keyword:'', trigger:'', effect:'自ユニット一体に+2/+2バフ', aiRole:''},
  {id:'c70', cost:2, name:'茨の檻', type:'陣地', atk:0, hp:0, keyword:'', trigger:'相手ターン終了時', effect:'相手に1点ダメージ', aiRole:''},
  {id:'c71', cost:2, name:'ダモクレスの剣', type:'スペル', atk:0, hp:0, keyword:'', trigger:'', effect:'敵ユニット一体に、そのユニットのATKと同値のダメージ', aiRole:''},
  {id:'c72', cost:4, name:'蒼波', type:'スペル', atk:0, hp:0, keyword:'', trigger:'', effect:'敵ユニットに1点×3回ダメージ。倒すたびに次のユニットへ移る', aiRole:'boardClear'},
  {id:'c73', cost:6, name:'リリス', type:'ユニット', atk:2, hp:3, keyword:'', trigger:'登場時', effect:'敵ユニット一体を完全無効化（キーワード・効果をすべて除去。障壁は無効）', aiRole:''},
  {id:'c74', cost:4, name:'メガイラ', type:'ユニット', atk:2, hp:4, keyword:'', trigger:'被ダメ時', effect:'このユニットまたは自プレイヤーがダメージを受けたとき、最もHPが低い敵ユニット一体に1点ダメージ', aiRole:''},
  {id:'c75', cost:3, name:'ケイオスマジック', type:'スペル', atk:0, hp:0, keyword:'', trigger:'', effect:'このゲーム中、シジルをターンに3回まで使用できる', aiRole:''},
  {id:'c76', cost:10, name:'星を落とす魔法', type:'スペル', atk:0, hp:0, keyword:'至高', trigger:'', effect:'相手プレイヤーに8点ダメージ', aiRole:'finisher'},
  {id:'c77', cost:4, name:'シームルグ', type:'ユニット', atk:3, hp:4, keyword:'', trigger:'登場時', effect:'自分の場に他にユニットが2体以上いるとき、睡眠にならない', aiRole:''},
  {id:'c78', cost:3, name:'生命の冒涜', type:'スペル', atk:0, hp:0, keyword:'', trigger:'', effect:'ユニット一体を破壊し、そのユニットのコスト÷2（切り上げ）/同値のキメラトークンを破壊されたユニットの場に召喚', aiRole:'removal'},
  {id:'c79', cost:5, name:'魔力溢れる遺跡', type:'陣地', atk:0, hp:0, keyword:'', trigger:'', effect:'場にある限り、互いの手札のカードコストを半分（切り上げ）にする', aiRole:''},
  {id:'c80', cost:6, name:'アヌビスの天秤', type:'スペル', atk:0, hp:0, keyword:'', trigger:'', effect:'敵ユニット一体に1点ダメージを与え、その後そのユニットを破壊する', aiRole:''},
  {id:'c81', cost:7, name:'メイルシュトローム', type:'スペル', atk:0, hp:0, keyword:'', trigger:'', effect:'敵ユニットに2点×4回ダメージ。倒すたびに次のユニットへ移る', aiRole:'boardClear'},
  {id:'c82', cost:5, name:'ウィリー・ウィンキー', type:'ユニット', atk:4, hp:4, keyword:'', trigger:'登場時', effect:'敵ユニット2体を睡眠にする', aiRole:''},
  {id:'c83', cost:4, name:'マンドラゴラ農園', type:'陣地', atk:0, hp:0, keyword:'', trigger:'自ターン終了時', effect:'敵ユニット一体に睡眠を付与する', aiRole:''},
  {id:'c84', cost:4, name:'オートマタ', type:'ユニット', atk:2, hp:5, keyword:'', trigger:'相手スペル・陣地使用時', effect:'相手がスペルまたは陣地を使用するたびに、相手プレイヤーに2点ダメージ', aiRole:''},
  {id:'c85', cost:7, name:'魔女の工房', type:'陣地', atk:0, hp:0, keyword:'至高', trigger:'自ターン開始時', effect:'手札のコストが最も高いカードのコストを2下げる', aiRole:''},
  {id:'c86', cost:8, name:'ハルマゲドン', type:'スペル', atk:0, hp:0, keyword:'', trigger:'', effect:'全ての場のユニットと陣地を破壊する', aiRole:'boardClear'},
  {id:'c87', cost:2, name:'オドの還元', type:'スペル', atk:0, hp:0, keyword:'至高', trigger:'', effect:'あなたの最大マナを1増やす', aiRole:''},
  {id:'c88', cost:10, name:'エリザベート', type:'ユニット', atk:5, hp:5, keyword:'', trigger:'登場時', effect:'相手に5点ダメージ。あなたを5点回復', aiRole:'removal'},
  {id:'c89', cost:3, name:'マンドラゴラ', type:'ユニット', atk:2, hp:1, keyword:'', trigger:'登場時', effect:'敵ユニット一体を睡眠にする', aiRole:''},
  {id:'c90', cost:1, name:'鏡写し', type:'スペル', atk:0, hp:0, keyword:'', trigger:'', effect:'ユニット一体のATKとHPを入れ替える', aiRole:'debuff'},
  {id:'c91', cost:6, name:'ワイトキング', type:'ユニット', atk:3, hp:3, keyword:'速攻', trigger:'登場時', effect:'デッキの残り枚数が10枚未満の場合、+5/+5を得る', aiRole:'finisher'},
  {id:'c92', cost:4, name:'アラクネ', type:'ユニット', atk:2, hp:4, keyword:'', trigger:'相手召喚時', effect:'相手が手札からユニットを召喚するたびに、そのユニットに2点ダメージ', aiRole:'trap'},];

const SIGIL_LIST = [
  {id:'burn', name:'焦熱', icon:'🔥', cost:2, desc:'相手または敵ユニット一体に1点ダメージ'},
  {id:'mid', name:'召喚', icon:'⚔️', cost:2, desc:'1/1トークンを召喚'},
  {id:'draw', name:'叡智', icon:'📚', cost:2, desc:'1枚ドローする'},
  {id:'heal', name:'治癒', icon:'💚', cost:2, desc:'自分または自ユニット一体に2点回復'},
  {id:'buff', name:'鼓舞', icon:'💪', cost:2, desc:'自ユニット一体に+1/0バフ'},
  {id:'debuff', name:'衰弱', icon:'🌀', cost:2, desc:'敵ユニット一体に-1/0デバフ'},
];
